version: "3"
services:
  www:
    build: .
    ports:
      - "80:80"
    networks:
      - default
    environment:
      - DB_HOST=db 
    volumes:
      - ".:/var/www"       
  db:
    image: mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    # volumes:
    #   - "./scripts/database.sql:/docker-entrypoint-initdb.d/1.sql"